### ISSUE TITLE
Trying to build this browser for Fedora , and been getting build errors

### ISSUE THREAD

**Issue by pieckenst** [dr460nf1r3/firedragon-browser#57]
So i've been trying to make a package of this browser for fedora , and had this build error occur after fixing a bunch of rpm spec file errors
```
 0:07.49 creating ./config.data
 0:07.50 Traceback (most recent call last):
 0:07.50   File "/builddir/build/BUILD/firedragon-109.0/firefox-109.0/configure.py", line 346, in <module>
 0:07.50     sys.exit(main(sys.argv))
 0:07.50              ^^^^^^^^^^^^^^
 0:07.50   File "/builddir/build/BUILD/firedragon-109.0/firefox-109.0/configure.py", line 128, in main
 0:07.50     sandbox.run(os.path.join(os.path.dirname(__file__), "moz.configure"))
 0:07.50   File "/builddir/build/BUILD/firedragon-109.0/firefox-109.0/python/mozbuild/mozbuild/configure/__init__.py", line 567, in run
 0:07.50     func(*args)
 0:07.50   File "/builddir/build/BUILD/firedragon-109.0/firefox-109.0/python/mozbuild/mozbuild/configure/__init__.py", line 618, in _value_for
 0:07.50     return self._value_for_depends(obj)
 0:07.50            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:07.51   File "/builddir/build/BUILD/firedragon-109.0/firefox-109.0/python/mozbuild/mozbuild/util.py", line 1063, in method_call
 0:07.51     cache[args] = self.func(instance, *args)
 0:07.51                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:07.51   File "/builddir/build/BUILD/firedragon-109.0/firefox-109.0/python/mozbuild/mozbuild/configure/__init__.py", line 627, in _value_for_depends
 0:07.51     value = obj.result()
 0:07.51             ^^^^^^^^^^^^
 0:07.51   File "/builddir/build/BUILD/firedragon-109.0/firefox-109.0/python/mozbuild/mozbuild/util.py", line 1063, in method_call
 0:07.51     cache[args] = self.func(instance, *args)
 0:07.51                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:07.51   File "/builddir/build/BUILD/firedragon-109.0/firefox-109.0/python/mozbuild/mozbuild/configure/__init__.py", line 163, in result
 0:07.51     return self._func(*resolved_args)
 0:07.51            ^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:07.51   File "/builddir/build/BUILD/firedragon-109.0/firefox-109.0/python/mozbuild/mozbuild/configure/__init__.py", line 1310, in wrapped
 0:07.51     return new_func(*args, **kwargs)
 0:07.51            ^^^^^^^^^^^^^^^^^^^^^^^^^
 0:07.51   File "/builddir/build/BUILD/firedragon-109.0/firefox-109.0/build/moz.configure/old.configure", line 299, in old_configure
 0:07.51     exec(code, raw_config)
 0:07.51   File "config.data", line 69, in <module>
 0:07.51     (''' STL_FLAGS ''', list(split(r''' -I/builddir/build/BUILD/firedragon-109.0/firefox-109.0/%{PWD@Q}/obj/dist/stl_wrappers '''))),
 0:07.51                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:07.51   File "/builddir/build/BUILD/firedragon-109.0/firefox-109.0/python/mozbuild/mozbuild/shellutil.py", line 176, in split
 0:07.51     return _ClineSplitter(s).result
 0:07.51            ^^^^^^^^^^^^^^^^^
 0:07.51   File "/builddir/build/BUILD/firedragon-109.0/firefox-109.0/python/mozbuild/mozbuild/shellutil.py", line 66, in __init__
 0:07.51     self._parse_unquoted()
 0:07.51   File "/builddir/build/BUILD/firedragon-109.0/firefox-109.0/python/mozbuild/mozbuild/shellutil.py", line 117, in _parse_unquoted
 0:07.51     raise MetaCharacterException(match["special"])
 0:07.51 mozbuild.shellutil.MetaCharacterException: {
 Config object not found by mach.
*** Fix above errors and then restart with "./mach build"
error: Bad exit status from /var/tmp/rpm-tmp.0He76r (%build)
```
Here is the rpm spec file https://github.com/pieckenst/firedragon-rpmspec/blob/main/firedragon.spec
And here is the repository where i have been trying to compile the browser https://copr.fedorainfracloud.org/coprs/rsncra/firedragon/

**Comment by trickypr** [comment]
This was caused by an incorrect build flag:
```
echo "mk_add_options MOZ_OBJDIR=%{PWD@Q}/obj" >> .mozconfig
```
